# Generated by Django 5.1.3 on 2026-07-01 22:23

import django.db.models.deletion
import singledrive_api.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singledrive_api', '0002_pelicula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('total_size', models.BigIntegerField()),
                ('offset', models.BigIntegerField(default=0)),
                ('temp_file_path', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('complete', 'Complete'), ('expired', 'Expired')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to=singledrive_api.models.drive_file_upload_path)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='thumbs/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='thumbs/')),
                ('exif_data', models.JSONField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='singledrive_api.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.AddField(
            model_name='drivefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='singledrive_api.folder'),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='singledrive_api.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent', 'is_deleted'], name='singledrive_owner_i_85ecd5_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_shared'], name='singledrive_is_shar_628546_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['owner', 'folder', 'is_deleted'], name='singledrive_owner_i_8078eb_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['owner', 'file_type', 'is_deleted'], name='singledrive_owner_i_a65dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['owner', 'is_deleted', 'created_at'], name='singledrive_owner_i_578cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['file_hash'], name='singledrive_file_ha_df60fb_idx'),
        ),
        migrations.AddIndex(
            model_name='drivefile',
            index=models.Index(fields=['name'], name='singledrive_name_f53e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkedupload',
            index=models.Index(fields=['owner', 'status'], name='singledrive_owner_i_e2960e_idx'),
        ),
    ]
